# Generated by Django 3.0.8 on 2020-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200727_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
