# Generated by Django 3.0.8 on 2020-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paquete_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'En bodega'), (1, 'En tránsito'), (2, 'Entregado')]),
        ),
    ]
